FROM debian:buster-slim

MAINTAINER Ruben

# Instal·lació de paquets necessaris
RUN apt-get update && apt-get install -y --no-install-recommends  \
    initscripts \
    quagga-ripd \
    iputils-ping \
    traceroute

ADD ./prac7_config_rip.sh /root
WORKDIR /root
CMD [ "/bin/bash" ]
